config/routes.rb
TwitterCloneRails::Application.routes.draw do
  root to: 'users#index'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/timeline', to: 'users#timeline', as: 'timeline'
  get '/mentions', to: 'users#mentions', as: 'mentions'

  get '/users', to: 'users#index'
  
  resources :users, only: [:create]
  resources :statuses, only: [:new, :create, :show]
  resources :hashtags, only: [:show]

  get '/:username', to: 'users#show', as: 'user'
  post '/:username/follow', to: 'users#follow', as: 'follow_user'
  post '/:username/unfollow', to: 'users#unfollow', as: 'unfollow_user'
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :user
  belongs_to :status

  default_scope { order('created_at DESC') }

  def mark_viewed!
    self.update(viewed_at: Time.now)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :leader, class_name: 'User', foreign_key: 'leader_id'
  belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :mentions

  validates :body, presence: true, length: {minimum: 5}

  default_scope { order('created_at DESC') }

  after_save :extract_mentions

  def extract_mentions
    mentions = self.body.scan(/(?<=@)[A-Za-z0-9]+/) 
    mentions.each do |mention|
      Mention.create(user: User.find_by(username: mention), status: self) if User.find_by(username: mention)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false

  has_many :statuses
  has_many :mentions

  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'leader_id'
  has_many :followers, through: :follower_relationships, source: :follower
  
  has_many :following_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
  has_many :followings, through: :following_relationships, source: :leader

  validates :username, presence: true, length: {minimum: 3}, uniqueness: true
  validates :email, presence: true
  validates :password, presence: true, length: {minimum: 8}, on: :create

  def to_param
    self.username
  end

  def unread_mentions
    self.mentions.where(viewed_at: nil)
  end

  def num_unread_mentions
    unread_mentions.count
  end

  def mark_unread_mentions!
    self.unread_mentions.each do |mention|
      mention.mark_viewed!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    access_denied unless logged_in?
  end

  def access_denied
    flash[:error] = 'You must be logged in to do that'
    redirect_to login_path
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :require_user

  def show
    @statuses = Status.where("body LIKE ?", "%##{params[:id]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [:destroy]

  def new
    
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      flash[:notice] = "You've logged in"
      session[:user_id] = user.id
      redirect_to timeline_path
    else
      flash.now[:error] = "There's something wrong with your username or password"
      render :new
    end
  end

  def destroy
    flash[:notice] = "You've logged out"
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    @status.creator = current_user

    if @status.save
      flash[:notice] = 'You created a new status'
      redirect_to user_path(@status.creator)
    else
      render :new
    end
  end

  private

  def status_params
    params.require(:status).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :follow, :unfollow]
  before_action :require_user, only: [:index, :show, :follow, :unfollow, :timeline]
  before_action :require_different_user, only: [:follow, :unfollow]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'You registered successfully'
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show; end

  def follow
    if @user
      current_user.followings << @user
      flash[:notice] = "You are now following #{@user.username}"
    else
      flash[:error] = "Follow was unsuccessful. Try again."
    end

    redirect_to :back
  end

  def unfollow
    if @user
      current_user.followings.delete(@user)
      flash[:notice] = "You stopped following #{@user.username}"
    else
      flash[:error] = "Unfollow was unsuccessful. Try again"
    end

    redirect_to :back
  end

  def timeline
    @statuses = []
    current_user.followings.each do |user|
      @statuses << user.statuses
    end
    @statuses.flatten!.sort_by { |s| s.created_at } if !@statuses.empty?
  end

  def mentions
    current_user.mark_unread_mentions!
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find_by(username: params[:username])
  end

  def require_different_user
    if @user == current_user
      flash[:error] = "You're not allowed to do that"
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_datetime(dt)
    dt.strftime("%b %d, %H:%M") # Dec 21, 18:05
  end

  def linkify_hashtags(str)
    str.gsub(/#(\S+[^\W])/, "<a href='/hashtags/\\1'>#\\1</a>").html_safe
  end

  def linkify_mentions(str)
    str.gsub(/@(\S+[^\W])/, "<a href='/\\1'>@\\1</a>").html_safe

    # str.gsub /@(\S+[^\W])/  do |match|
    #   match = match.slice(1...match.size)
    #   User.find_by(username: match) ? "<a href='/#{match}'>@#{match}</a>".html_safe : "@#{match}".html_safe
    # end
  end

  def linkify(str)
    str = linkify_hashtags(str)
    str = linkify_mentions(str)
  end
end

app/views/hashtags/show.html.erb
<%= render 'shared/header', title: "Tweets with ##{params[:id]}" %>

<%= render @statuses %>

app/views/layouts/_messages.html.erb
<% if flash.keys.any? %>
  <% flash.keys.each do |key| %>
    <div class="alert alert-<%= key == :notice ? 'success' : 'danger' %>"><%= flash[key] %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default", role='navigation'>
  <div class="container">
    <ul class="nav navbar-nav">
      <% if logged_in? %>
        <li><%= link_to 'Home', timeline_path %></li>
        <li><%= link_to current_user.num_unread_mentions == 0 ? "Mentions" : "Mentions (#{current_user.num_unread_mentions})", mentions_path %></li>
        <li><%= link_to 'All Users', users_path %></li>
        <li><%= link_to 'New Status', new_status_path %></li>
        <li><%= link_to 'Logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Register', register_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterCloneRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navigation' %>
  <div class='container'>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">There were some errors</div>
    <div class="panel-body text-danger">
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<h2 class="lead"><%= title %></h2>
<hr>

app/views/statuses/_status.html.erb
<div class="clearfix">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><%= linkify(status.body) %></p>
      <p>by <%= link_to status.creator.username, user_path(status.creator) %> at <strong><%= status.created_at %></strong></p>
    </div>
  </div>
</div>

app/views/statuses/new.html.erb
<%= render 'shared/header', title: 'Create a New Status' %>


<div class="col-sm-6">
  <%= render 'shared/error', obj: @status %>
  <%= form_for @status, html: {role: 'form'} do |f| %>
    <div class='form-group'>
      <%= f.label :body, class: 'sr-only' %>
      <br/>
      <%= f.text_area :body, rows: 4, placeholder: 'Type your status here', class: 'form-control' %>
      </br>
      <%= f.submit 'Create Status', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'shared/header', title: 'All Users' %>

<ul class="list-unstyled">
  <% @users.each do |user| %>
      <li><%= link_to "@#{user.username}", user_path(user) %></li>
  <% end %>
</ul>

app/views/users/mentions.html.erb
<%= render 'shared/header', title: "Mentions" %>

<div class="col-sm-6">
  <% current_user.mentions.each do |mention| %>
    <%= render mention.status %>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'shared/header', title: 'Register' %>

<%= render 'shared/error', obj: @user %>

<div class="col-sm-6">
<%= form_for @user, html: {role: 'form'} do |f| %>
  <div class="form-group">
    <%= f.label :username, class: 'control-label' %>
    <%= f.text_field :username, class: 'form-control' %>
    <br/>
  </div>
  <div class='form-group'>
    <%= f.label :email, class: 'control-label' %>
    <%= f.text_field :email, class: 'form-control' %>
    <br/>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'control-label' %>
    <%= f.password_field :password, class: 'form-control' %>
    <br/>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/users/show.html.erb
<%= link_to user_path(@user) do %>
  <%= render 'shared/header', title: "@#{@user.username}" %>
<% end %>

<% if logged_in? && @user != current_user %>
  <% if !current_user.following_ids.include?(@user.id) %>
    <%= link_to follow_user_path(@user), method: 'post' do %>
      <span class="glyphicon glyphicon-plus"></span> <strong>Follow <%= @user.username %></strong>
    <% end %>
    </br>
    </br>
  <% else %>
    <%= link_to unfollow_user_path(@user), method: 'post' do %>
      <span class="glyphicon glyphicon-minus"></span> <strong>Unfollow <%= @user.username %></strong>
    <% end %>
    </br>
    </br>
  <% end %>
<% end %>

<div class="col-sm-6">
  <%= render @user.statuses %>
</div>

<div class="col-sm-6">
  <h4>Followers</h4>

  <% @user.followers.each do |follower| %>
    <p><%= link_to "@#{follower.username}", user_path(follower) %></p>
  <% end %>

  <h4>Following</h4>

  <% @user.followings.each do |following| %>
    <p><%= link_to "@#{following.username}", user_path(following) %></p>
  <% end %>
</div>

app/views/users/timeline.html.erb
<%= render 'shared/header', title: "Timeline" %>

<div class="col-sm-6">
  <%= render @statuses %>
</div>